default_platform(:android)

platform :android do
  desc "Build the Android App Bundle"
  lane :build_aab do
    gradle(
      task: "bundle",
      build_type: "Release",
      # This is the important part:
      use_gradlew: false
    )
  end
end
