default_platform(:android)

platform :android do
  desc "Build the Android App Bundle"
  lane :build_aab do
    gradle(
      task: "bundle",
      build_type: "Release",
      # Point Fastlane directly to your script
      gradle_path: "./gradlew"
    )
  end
end
